### ISSUE TITLE
Recurrence analysis does not work anymore

### ISSUE THREAD

**Issue by pucicu** [JuliaDynamics/DynamicalSystems.jl#180]
Hi,

today I re-run my code published at https://github.com/pucicu/RP_Speed_Test, but the Julia code is not working anymore. I get the error `ERROR: UndefVarError: RecurrenceMatrix not defined`. It seems to be a feature of Julia that after a few weeks my code is not working anymore. It happened already several times.

Best
N

**Comment by Datseris** [comment]
1. which code **exactly** you run, which Julia file?
2. What are your package versions? All of them, `DynamicalSystems` and `RecurrenceAnalysis`. Use this command to find out and post: 
```julia
using Pkg
Pkg.status([
    "DynamicalSystems",
    "DelayEmbeddings", "RecurrenceAnalysis",
    "DynamicalSystemsBase", "ChaosTools",
    "Entropies",];
    mode = PKGMODE_MANIFEST
)
```

In the future please follow the bug report template, it simply makes it much faster to find the problem, both for me, and for you :)

RecurrenceAnalysis just moved from LightGraphs.jl to Graphs.jl in version 1.8, that may be relevant. 

In any case, this is not a feature of Julia because my code works without a problem:  https://juliadynamics.github.io/DynamicalSystems.jl/v2.3/rqa/rplots/   with package versions:  https://juliadynamics.github.io/DynamicalSystems.jl/v2.3/#Version-numbers

**Comment by pucicu** [comment]
it seems it was now necessary to call `using RecurrenceAnalysis` before using the recurrence analysis. in the last months it was sufficient to call `using DynamicalSystems`. now I updated and it seems to be enough again to call DynamicalSystems. I have no idea why it was not working before.

you can find the exact script in the mentioned github repo. you might find it interesting because it compares with pyunicorn implementation. ;-)
