### ISSUE TITLE
`GlobalRecurrenceRate`vs. `fixedrate`

### ISSUE THREAD

**Issue by pucicu** [JuliaDynamics/DynamicalSystems.jl#240]
Perhaps it was somewhere mentioned, but I cannot find it. The way how to get a _fixedrate_ RP seems to have been changed. I now get warnings in the form
```
 Warning: Providing keyword `fixedrate` is deprecated. Use `GlobalRecurrenceRate`.
└ @ RecurrenceAnalysis ~/.julia/packages/RecurrenceAnalysis/Eo1Rq/src/matrices/recurrence_matrix_types.jl:148
```
When looking at the tutorial, e.g., at <https://juliadynamics.github.io/RecurrenceAnalysis.jl/v2.0/rplots/>, I can only find the outdated
```
R = RecurrenceMatrix(Y, 0.25; fixedrate=true)
```

The only help entry I could find for `GlobalRecurrenceRate`was this at <https://juliadynamics.github.io/RecurrenceAnalysis.jl/v2.0/rplots/#RecurrenceAnalysis.GlobalRecurrenceRate>. But I do not understand how I have to replace my command with the depreceated `fixedrate`argument
```
R1 = RecurrenceMatrix(x, RR, fixedrate = true; metric = Euclidean(), parallel = true);
```
by the new `GlobalRecurrenceRate`.

I'm sure it is completely easy and simple. Perhaps the tutorial could also be updated?

Thanks for any hint!
Norbert

**Comment by Datseris** [comment]
Hi,

yes, the line you mention in the tutorial
```julia
R = RecurrenceMatrix(Y, 0.25; fixedrate=true)
```
is indeed outdate. The correct way to do things now is by giving the `GlobalRecurrenceRate` as a **second argument** to the input of a recurrence matrix. Let's have a look at the docstring of `RecurrenceMatrix`:

![image](https://github.com/JuliaDynamics/DynamicalSystems.jl/assets/19669089/b9779c3b-74e5-4f81-b5c5-e264327c8da0)

Clicking the [AbstractRecurrenceType](https://juliadynamics.github.io/RecurrenceAnalysis.jl/stable/rplots/#RecurrenceAnalysis.AbstractRecurrenceType) hyperlink shows:

![image](https://github.com/JuliaDynamics/DynamicalSystems.jl/assets/19669089/dc2b35ac-d53d-4aee-b835-5c999f0d1782)

so you just give any of these options instead of the `ε` number as second argument to the recurrence matrix. This approach of specifying the recurrences by an explicit input type (instead of a plethora of interlaced keywords) leads to incredible simpler source code, and also source code that is easier to maintain and bugfix.

In the meantime, I'll fix the tutorial with a simple PR now.

**Comment by pucicu** [comment]
Great! Thanks! After several attempts, I finally figured out what you meant. Examples would really be very helpful. Obviously, it should be something like this:
```
R = RecurrenceMatrix(tr, GlobalRecurrenceRate(RR); metric = Euclidean(), parallel = true);
```

(now I also have seen that you updated the tutorial! Thanks!)

**Comment by Datseris** [comment]
> Examples would really be very helpful.

It is very easy to contribute examples to this package, and any other module of DynamicalSystems.jl. Simply go to the docs, click the edit button top right
![image](https://github.com/JuliaDynamics/DynamicalSystems.jl/assets/19669089/f904842e-f18c-4463-82bc-e0f8447a8a91)
and add your example. Contributions are welcomed!
